# Model config
model:
  name: "Nous Hermes 2 Pro"  # Unused, for information purposes only
  api_url: "https://curated.aleph.cloud/vm/84df52ac4466d121ef3bb409bb14f315de7be4ce600e8948d71df6485aa5bcc3/completion"
  engine: "llamacpp"

  max_prompt_tokens: 8000

# Agent config
agent:
  # Max number of times the agent can call itself back
  max_recurse_depth: 3
